version: '3.8'

services:
  backend:
    build: .
    volumes:
      - './millenium_falcon_challenge:/app/millenium_falcon_challenge'
      - './examples:/app/examples'
    ports:
      - 5000:5000
    command: poetry run uvicorn millenium_falcon_challenge.back_end:app --reload --host 0.0.0.0 --port 5000
  frontend:
    build: frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    command: npm run serve
