# generated by datamodel-codegen:
#   filename:  empire.json
#   timestamp: 2022-01-05T14:15:26+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class BountyHunter(BaseModel):
    class Config:
        allow_mutation = False

    planet: str
    day: int


class Empire(BaseModel):
    class Config:
        allow_mutation = False

    countdown: int
    bounty_hunters: List[BountyHunter]
