# generated by datamodel-codegen:
#   filename:  millennium-falcon.json
#   timestamp: 2022-01-05T14:15:21+00:00

from __future__ import annotations

from pydantic import BaseModel


class MillenniumFalcon(BaseModel):
    class Config:
        allow_mutation = False

    autonomy: int
    departure: str
    arrival: str
    routes_db: str
