# generated by datamodel-codegen:
#   filename:  empire.json
#   timestamp: 2022-01-05T14:15:26+00:00

from __future__ import annotations

from pydantic import BaseModel


class OddsOfSuccess(BaseModel):
    class Config:
        allow_mutation = False

    odds_of_success: float
