# generated by datamodel-codegen:
#   filename:  answer.json
#   timestamp: 2022-01-05T14:15:31+00:00

from __future__ import annotations

from pydantic import BaseModel


class Answer(BaseModel):
    class Config:
        allow_mutation = False

    odds: float
